### ISSUE TITLE
No upload option for env

### ISSUE THREAD

**Issue by quartox** [blaze/rambling#109]
I have been mulling over writing a PR to allow users to set environment variables (`CONDA_PREFIX` and `PYTHON_BIN`) and not upload the environment at all. This seems like it wouldn't be too difficult based on what I have already observed with knit, but I wanted to see if this is possible and discuss API choices if it is.

**Comment by martindurant** [comment]
We have just been working on exactly this.
The idea is that you can pass any files, and that those starting with hdfs:// are assumed to already exist on the cluster, and any ending with .zip are assumed to need decompression in the container.
PR #108 extends this to dask_yarn, so that `env=` can be an existing HDFS zip file.
